import type { Metadata } from "next";
import "./globals.css";
import { Footer, Header } from "@/components/common";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-screen w-full">
        <Header />
        <main className="">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
